language: python
python:
  - 2.7
  - 3.6
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=1.24.1
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose -f tests/docker-compose.yml --no-ansi up -d
  - docker-compose -f tests/docker-compose.yml --no-ansi ps
  - PROXY_HOST=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' tests_browsermobproxy_1)
install:
  - pip install -r requirements.txt
  - pip install -r tests/tests-requirements.txt
  - pip install .
script:
  - robot -x xunit.xml -v PROXY_HOST:$PROXY_HOST tests
